/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package automationtesttimecalculation;

/**
 *
 * @author PKaml7162859
 */

public class TesttimeDataManagementGUI extends javax.swing.JFrame {

  /**
   * Creates new form GUI
   */
  public TesttimeDataManagementGUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    TitleProgram = new javax.swing.JLabel();
    labelH_Configuration = new javax.swing.JLabel();
    labelH_status = new javax.swing.JLabel();
    label_Status = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    labelH_MainDIR = new javax.swing.JLabel();
    TextField_MainDIR = new javax.swing.JTextField();
    labelH_LastExecuteDate = new javax.swing.JLabel();
    labelH_Calendar = new javax.swing.JLabel();
    TextField_LastExecuteDate = new javax.swing.JTextField();
    TextField_Calendar = new javax.swing.JTextField();
    TextField_MasterScript = new javax.swing.JTextField();
    TextField_ExecuteScript = new javax.swing.JTextField();
    TextField_BatchExecuteSPSS = new javax.swing.JTextField();
    TextField_ResultAll = new javax.swing.JTextField();
    TextField_ResultByTestCode = new javax.swing.JTextField();
    labelH_ExecuteScript = new javax.swing.JLabel();
    labelH_MasterScript = new javax.swing.JLabel();
    labelH_ResultByTestCode = new javax.swing.JLabel();
    labelH_ResultAll = new javax.swing.JLabel();
    labelH_BatchExecuteSPSS = new javax.swing.JLabel();
    labelH_Product = new javax.swing.JLabel();
    TextField_Product = new javax.swing.JTextField();
    labelH_BatchMasterSPSS = new javax.swing.JLabel();
    TextField_BatchMasterSPSS = new javax.swing.JTextField();
    labelH_BatchExecuteSPSS1 = new javax.swing.JLabel();
    TextField_SPSSLogFile = new javax.swing.JTextField();
    labelH_Product1 = new javax.swing.JLabel();
    labelH_ExecuteScript1 = new javax.swing.JLabel();
    TextField_SPSSScriptFile = new javax.swing.JTextField();
    TextField_SPSSUserName = new javax.swing.JTextField();
    labelH_BatchMasterSPSS1 = new javax.swing.JLabel();
    TextField_SPSSPassword = new javax.swing.JTextField();
    TextField_SPSSPortName = new javax.swing.JTextField();
    TextField_SPSSHostName = new javax.swing.JTextField();
    labelH_ResultAll1 = new javax.swing.JLabel();
    labelH_ResultByTestCode1 = new javax.swing.JLabel();
    labelH_Product2 = new javax.swing.JLabel();
    labelH_ResultByTestCode2 = new javax.swing.JLabel();
    labelH_ResultAll2 = new javax.swing.JLabel();
    labelH_BatchExecuteSPSS2 = new javax.swing.JLabel();
    labelH_BatchMasterSPSS2 = new javax.swing.JLabel();
    labelH_ExecuteScript2 = new javax.swing.JLabel();
    TextField_DBHostName = new javax.swing.JTextField();
    TextField_DBPortName = new javax.swing.JTextField();
    TextField_DBUsername = new javax.swing.JTextField();
    TextField_DBPassword = new javax.swing.JTextField();
    TextField_DBName = new javax.swing.JTextField();
    TextField_DBTableName = new javax.swing.JTextField();
    labelH_status1 = new javax.swing.JLabel();
    label_excTime = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setAlwaysOnTop(true);
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
    });

    TitleProgram.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    TitleProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automationtesttimecalculation/download.jpg"))); // NOI18N
    TitleProgram.setText("Java:   Testtime Data Management");

    labelH_Configuration.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    labelH_Configuration.setText("Configuration:");

    labelH_status.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    labelH_status.setText("Status:");

    label_Status.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
    label_Status.setForeground(new java.awt.Color(255, 0, 0));
    label_Status.setText("default status.");
    label_Status.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        label_StatusPropertyChange(evt);
      }
    });

    jPanel1.setBackground(new java.awt.Color(232, 229, 229));

    labelH_MainDIR.setText("MainDIR");

    TextField_MainDIR.setEditable(false);
    TextField_MainDIR.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_MainDIRActionPerformed(evt);
      }
    });

    labelH_LastExecuteDate.setText("LastExecuteDate");

    labelH_Calendar.setText("Calendar file");

    TextField_LastExecuteDate.setEditable(false);
    TextField_LastExecuteDate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_LastExecuteDateActionPerformed(evt);
      }
    });

    TextField_Calendar.setEditable(false);
    TextField_Calendar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_CalendarActionPerformed(evt);
      }
    });

    TextField_MasterScript.setEditable(false);
    TextField_MasterScript.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_MasterScriptActionPerformed(evt);
      }
    });

    TextField_ExecuteScript.setEditable(false);
    TextField_ExecuteScript.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_ExecuteScriptActionPerformed(evt);
      }
    });

    TextField_BatchExecuteSPSS.setEditable(false);
    TextField_BatchExecuteSPSS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_BatchExecuteSPSSActionPerformed(evt);
      }
    });

    TextField_ResultAll.setEditable(false);
    TextField_ResultAll.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_ResultAllActionPerformed(evt);
      }
    });

    TextField_ResultByTestCode.setEditable(false);
    TextField_ResultByTestCode.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_ResultByTestCodeActionPerformed(evt);
      }
    });

    labelH_ExecuteScript.setText("ExecuteScript");

    labelH_MasterScript.setText("MasterScript");

    labelH_ResultByTestCode.setText("ResultByTestCode");

    labelH_ResultAll.setText("ResultAll");

    labelH_BatchExecuteSPSS.setText("BatchExecuteSPSS");

    labelH_Product.setText("Product");

    TextField_Product.setEditable(false);
    TextField_Product.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_ProductActionPerformed(evt);
      }
    });

    labelH_BatchMasterSPSS.setText("BatchMasterSPSS");

    TextField_BatchMasterSPSS.setEditable(false);
    TextField_BatchMasterSPSS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_BatchMasterSPSSActionPerformed(evt);
      }
    });

    labelH_BatchExecuteSPSS1.setText("SPSSUsername");

    TextField_SPSSLogFile.setEditable(false);
    TextField_SPSSLogFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_SPSSLogFileActionPerformed(evt);
      }
    });

    labelH_Product1.setText("SPSSScriptFile");

    labelH_ExecuteScript1.setText("SPSSHostName");

    TextField_SPSSScriptFile.setEditable(false);
    TextField_SPSSScriptFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_SPSSScriptFileActionPerformed(evt);
      }
    });

    TextField_SPSSUserName.setEditable(false);
    TextField_SPSSUserName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_SPSSUserNameActionPerformed(evt);
      }
    });

    labelH_BatchMasterSPSS1.setText("SPSSPortName");

    TextField_SPSSPassword.setEditable(false);
    TextField_SPSSPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_SPSSPasswordActionPerformed(evt);
      }
    });

    TextField_SPSSPortName.setEditable(false);
    TextField_SPSSPortName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_SPSSPortNameActionPerformed(evt);
      }
    });

    TextField_SPSSHostName.setEditable(false);
    TextField_SPSSHostName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_SPSSHostNameActionPerformed(evt);
      }
    });

    labelH_ResultAll1.setText("SPSSPassword");

    labelH_ResultByTestCode1.setText("SPSSLogFile");

    labelH_Product2.setText("DBTableName");

    labelH_ResultByTestCode2.setText("DBName");

    labelH_ResultAll2.setText("DBPassword");

    labelH_BatchExecuteSPSS2.setText("DBUsername");

    labelH_BatchMasterSPSS2.setText("DBPortName");

    labelH_ExecuteScript2.setText("DBHostName");

    TextField_DBHostName.setEditable(false);
    TextField_DBHostName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_DBHostNameActionPerformed(evt);
      }
    });

    TextField_DBPortName.setEditable(false);
    TextField_DBPortName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_DBPortNameActionPerformed(evt);
      }
    });

    TextField_DBUsername.setEditable(false);
    TextField_DBUsername.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_DBUsernameActionPerformed(evt);
      }
    });

    TextField_DBPassword.setEditable(false);
    TextField_DBPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_DBPasswordActionPerformed(evt);
      }
    });

    TextField_DBName.setEditable(false);
    TextField_DBName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_DBNameActionPerformed(evt);
      }
    });

    TextField_DBTableName.setEditable(false);
    TextField_DBTableName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextField_DBTableNameActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelH_MasterScript)
          .addComponent(labelH_ExecuteScript)
          .addComponent(labelH_BatchMasterSPSS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelH_Product2)
          .addComponent(labelH_ResultAll1)
          .addComponent(labelH_ResultByTestCode1)
          .addComponent(labelH_ResultAll)
          .addComponent(labelH_ResultByTestCode)
          .addComponent(labelH_BatchMasterSPSS2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_BatchExecuteSPSS2)
          .addComponent(labelH_ResultAll2)
          .addComponent(labelH_ResultByTestCode2)
          .addComponent(labelH_ExecuteScript2)
          .addComponent(labelH_BatchExecuteSPSS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_Product)
          .addComponent(labelH_BatchMasterSPSS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelH_BatchExecuteSPSS1)
          .addComponent(labelH_Product1)
          .addComponent(labelH_Calendar)
          .addComponent(labelH_ExecuteScript1)
          .addComponent(labelH_MainDIR)
          .addComponent(labelH_LastExecuteDate))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(TextField_SPSSPortName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_MasterScript, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_ExecuteScript, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_SPSSPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_ResultAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_ResultByTestCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_DBName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_DBPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_DBHostName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_DBUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_DBPortName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_BatchExecuteSPSS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_Product, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_BatchMasterSPSS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_SPSSLogFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_Calendar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_SPSSHostName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_SPSSUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_SPSSScriptFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_LastExecuteDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_MainDIR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TextField_DBTableName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(12, 12, 12))
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TextField_BatchExecuteSPSS, TextField_Calendar, TextField_ExecuteScript, TextField_LastExecuteDate, TextField_MainDIR, TextField_MasterScript, TextField_Product, TextField_ResultAll, TextField_ResultByTestCode});

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelH_BatchExecuteSPSS1, labelH_BatchExecuteSPSS2, labelH_BatchMasterSPSS1, labelH_BatchMasterSPSS2, labelH_Calendar, labelH_ExecuteScript, labelH_ExecuteScript1, labelH_ExecuteScript2, labelH_LastExecuteDate, labelH_MainDIR, labelH_MasterScript, labelH_Product, labelH_Product1, labelH_Product2, labelH_ResultAll, labelH_ResultAll1, labelH_ResultAll2, labelH_ResultByTestCode, labelH_ResultByTestCode1, labelH_ResultByTestCode2});

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TextField_DBHostName, TextField_DBName, TextField_DBPassword, TextField_DBPortName, TextField_DBTableName, TextField_DBUsername, TextField_SPSSScriptFile});

    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelH_MainDIR)
          .addComponent(TextField_MainDIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelH_LastExecuteDate)
          .addComponent(TextField_LastExecuteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(10, 10, 10)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelH_Calendar)
          .addComponent(TextField_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_MasterScript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_MasterScript))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_ExecuteScript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ExecuteScript))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_BatchMasterSPSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_BatchMasterSPSS))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_BatchExecuteSPSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_BatchExecuteSPSS))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_ResultAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ResultAll))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_ResultByTestCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ResultByTestCode))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_Product))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_SPSSHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ExecuteScript1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_SPSSPortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_BatchMasterSPSS1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_SPSSUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_BatchExecuteSPSS1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_SPSSPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ResultAll1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_SPSSLogFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ResultByTestCode1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_SPSSScriptFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_Product1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_DBHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ExecuteScript2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_DBPortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_BatchMasterSPSS2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_DBUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_BatchExecuteSPSS2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_DBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ResultAll2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_DBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_ResultByTestCode2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TextField_DBTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelH_Product2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TextField_BatchExecuteSPSS, TextField_Calendar, TextField_ExecuteScript, TextField_LastExecuteDate, TextField_MainDIR, TextField_MasterScript, TextField_Product, TextField_ResultAll, TextField_ResultByTestCode});

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelH_BatchExecuteSPSS, labelH_BatchExecuteSPSS1, labelH_BatchExecuteSPSS2, labelH_BatchMasterSPSS1, labelH_BatchMasterSPSS2, labelH_Calendar, labelH_ExecuteScript, labelH_ExecuteScript1, labelH_ExecuteScript2, labelH_LastExecuteDate, labelH_MainDIR, labelH_MasterScript, labelH_Product, labelH_Product1, labelH_Product2, labelH_ResultAll, labelH_ResultAll1, labelH_ResultAll2, labelH_ResultByTestCode, labelH_ResultByTestCode1, labelH_ResultByTestCode2});

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TextField_DBHostName, TextField_DBName, TextField_DBPassword, TextField_DBPortName, TextField_DBTableName, TextField_DBUsername, TextField_SPSSScriptFile});

    labelH_status1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    labelH_status1.setText("Execute time :");

    label_excTime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
    label_excTime.setForeground(new java.awt.Color(0, 102, 255));
    label_excTime.setText("00:00:00");
    label_excTime.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        label_excTimePropertyChange(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(TitleProgram)
        .addGap(117, 117, 117))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelH_status, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(label_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelH_Configuration)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelH_status1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(label_excTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TitleProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(label_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelH_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelH_status1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(label_excTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(20, 20, 20)
        .addComponent(labelH_Configuration)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void TextField_MainDIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MainDIRActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_MainDIRActionPerformed

  private void TextField_LastExecuteDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_LastExecuteDateActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_LastExecuteDateActionPerformed

  private void TextField_CalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_CalendarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_CalendarActionPerformed

  private void TextField_MasterScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MasterScriptActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_MasterScriptActionPerformed

  private void TextField_ExecuteScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ExecuteScriptActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_ExecuteScriptActionPerformed

  private void TextField_BatchExecuteSPSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_BatchExecuteSPSSActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_BatchExecuteSPSSActionPerformed

  private void TextField_ResultAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ResultAllActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_ResultAllActionPerformed

  private void TextField_ResultByTestCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ResultByTestCodeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_ResultByTestCodeActionPerformed

  private void TextField_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ProductActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_ProductActionPerformed

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    // TODO add your handling code here:
  }//GEN-LAST:event_formWindowClosed

  private void label_StatusPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_label_StatusPropertyChange

  }//GEN-LAST:event_label_StatusPropertyChange

  private void TextField_BatchMasterSPSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_BatchMasterSPSSActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_BatchMasterSPSSActionPerformed

  private void TextField_SPSSLogFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_SPSSLogFileActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_SPSSLogFileActionPerformed

  private void TextField_SPSSScriptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_SPSSScriptFileActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_SPSSScriptFileActionPerformed

  private void TextField_SPSSUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_SPSSUserNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_SPSSUserNameActionPerformed

  private void TextField_SPSSPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_SPSSPasswordActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_SPSSPasswordActionPerformed

  private void TextField_SPSSPortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_SPSSPortNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_SPSSPortNameActionPerformed

  private void TextField_SPSSHostNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_SPSSHostNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_SPSSHostNameActionPerformed

  private void TextField_DBHostNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DBHostNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_DBHostNameActionPerformed

  private void TextField_DBPortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DBPortNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_DBPortNameActionPerformed

  private void TextField_DBUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DBUsernameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_DBUsernameActionPerformed

  private void TextField_DBPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DBPasswordActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_DBPasswordActionPerformed

  private void TextField_DBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DBNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_DBNameActionPerformed

  private void TextField_DBTableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DBTableNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextField_DBTableNameActionPerformed

  private void label_excTimePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_label_excTimePropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_label_excTimePropertyChange

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info  javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(TesttimeDataManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(TesttimeDataManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(TesttimeDataManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(TesttimeDataManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//        //</editor-fold>
//        
//    /* Create and display the form */
//    
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        //new TesttimeDataManagementGUI().setVisible(true);
//       
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField TextField_BatchExecuteSPSS;
  private javax.swing.JTextField TextField_BatchMasterSPSS;
  private javax.swing.JTextField TextField_Calendar;
  private javax.swing.JTextField TextField_DBHostName;
  private javax.swing.JTextField TextField_DBName;
  private javax.swing.JTextField TextField_DBPassword;
  private javax.swing.JTextField TextField_DBPortName;
  private javax.swing.JTextField TextField_DBTableName;
  private javax.swing.JTextField TextField_DBUsername;
  private javax.swing.JTextField TextField_ExecuteScript;
  private javax.swing.JTextField TextField_LastExecuteDate;
  private javax.swing.JTextField TextField_MainDIR;
  private javax.swing.JTextField TextField_MasterScript;
  private javax.swing.JTextField TextField_Product;
  private javax.swing.JTextField TextField_ResultAll;
  private javax.swing.JTextField TextField_ResultByTestCode;
  private javax.swing.JTextField TextField_SPSSHostName;
  private javax.swing.JTextField TextField_SPSSLogFile;
  private javax.swing.JTextField TextField_SPSSPassword;
  private javax.swing.JTextField TextField_SPSSPortName;
  private javax.swing.JTextField TextField_SPSSScriptFile;
  private javax.swing.JTextField TextField_SPSSUserName;
  private javax.swing.JLabel TitleProgram;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel labelH_BatchExecuteSPSS;
  private javax.swing.JLabel labelH_BatchExecuteSPSS1;
  private javax.swing.JLabel labelH_BatchExecuteSPSS2;
  private javax.swing.JLabel labelH_BatchMasterSPSS;
  private javax.swing.JLabel labelH_BatchMasterSPSS1;
  private javax.swing.JLabel labelH_BatchMasterSPSS2;
  private javax.swing.JLabel labelH_Calendar;
  private javax.swing.JLabel labelH_Configuration;
  private javax.swing.JLabel labelH_ExecuteScript;
  private javax.swing.JLabel labelH_ExecuteScript1;
  private javax.swing.JLabel labelH_ExecuteScript2;
  private javax.swing.JLabel labelH_LastExecuteDate;
  private javax.swing.JLabel labelH_MainDIR;
  private javax.swing.JLabel labelH_MasterScript;
  private javax.swing.JLabel labelH_Product;
  private javax.swing.JLabel labelH_Product1;
  private javax.swing.JLabel labelH_Product2;
  private javax.swing.JLabel labelH_ResultAll;
  private javax.swing.JLabel labelH_ResultAll1;
  private javax.swing.JLabel labelH_ResultAll2;
  private javax.swing.JLabel labelH_ResultByTestCode;
  private javax.swing.JLabel labelH_ResultByTestCode1;
  private javax.swing.JLabel labelH_ResultByTestCode2;
  private javax.swing.JLabel labelH_status;
  private javax.swing.JLabel labelH_status1;
  private javax.swing.JLabel label_Status;
  private javax.swing.JLabel label_excTime;
  // End of variables declaration//GEN-END:variables

  /**
   * @return the TextField_BatchExecuteSPSS
   */
  public javax.swing.JTextField getTextField_BatchExecuteSPSS() {
    return TextField_BatchExecuteSPSS;
  }

  /**
   * @param TextField_BatchExecuteSPSS the TextField_BatchExecuteSPSS to set
   */
  public void setTextField_BatchExecuteSPSS(javax.swing.JTextField TextField_BatchExecuteSPSS) {
    this.TextField_BatchExecuteSPSS = TextField_BatchExecuteSPSS;
  }

  /**
   * @return the TextField_Calendar
   */
  public javax.swing.JTextField getTextField_Calendar() {
    return TextField_Calendar;
  }

  /**
   * @param TextField_Calendar the TextField_Calendar to set
   */
  public void setTextField_Calendar(javax.swing.JTextField TextField_Calendar) {
    this.TextField_Calendar = TextField_Calendar;
  }

  /**
   * @return the TextField_ExecuteScript
   */
  public javax.swing.JTextField getTextField_ExecuteScript() {
    return TextField_ExecuteScript;
  }

  /**
   * @param TextField_ExecuteScript the TextField_ExecuteScript to set
   */
  public void setTextField_ExecuteScript(javax.swing.JTextField TextField_ExecuteScript) {
    this.TextField_ExecuteScript = TextField_ExecuteScript;
  }

  /**
   * @return the TextField_LastExecuteDate
   */
  public javax.swing.JTextField getTextField_LastExecuteDate() {
    return TextField_LastExecuteDate;
  }

  /**
   * @param TextField_LastExecuteDate the TextField_LastExecuteDate to set
   */
  public void setTextField_LastExecuteDate(javax.swing.JTextField TextField_LastExecuteDate) {
    this.TextField_LastExecuteDate = TextField_LastExecuteDate;
  }

  /**
   * @return the TextField_MainDIR
   */
  public javax.swing.JTextField getTextField_MainDIR() {
    return TextField_MainDIR;
  }

  /**
   * @param TextField_MainDIR the TextField_MainDIR to set
   */
  public void setTextField_MainDIR(javax.swing.JTextField TextField_MainDIR) {
    this.TextField_MainDIR = TextField_MainDIR;
  }

  /**
   * @return the TextField_MasterScript
   */
  public javax.swing.JTextField getTextField_MasterScript() {
    return TextField_MasterScript;
  }

  /**
   * @param TextField_MasterScript the TextField_MasterScript to set
   */
  public void setTextField_MasterScript(javax.swing.JTextField TextField_MasterScript) {
    this.TextField_MasterScript = TextField_MasterScript;
  }

  /**
   * @return the TextField_Product
   */
  public javax.swing.JTextField getTextField_Product() {
    return TextField_Product;
  }

  /**
   * @param TextField_Product the TextField_Product to set
   */
  public void setTextField_Product(javax.swing.JTextField TextField_Product) {
    this.TextField_Product = TextField_Product;
  }

  /**
   * @return the TextField_ResultAll
   */
  public javax.swing.JTextField getTextField_ResultAll() {
    return TextField_ResultAll;
  }

  /**
   * @param TextField_ResultAll the TextField_ResultAll to set
   */
  public void setTextField_ResultAll(javax.swing.JTextField TextField_ResultAll) {
    this.TextField_ResultAll = TextField_ResultAll;
  }

  /**
   * @return the TextField_ResultByTestCode
   */
  public javax.swing.JTextField getTextField_ResultByTestCode() {
    return TextField_ResultByTestCode;
  }

  /**
   * @param TextField_ResultByTestCode the TextField_ResultByTestCode to set
   */
  public void setTextField_ResultByTestCode(javax.swing.JTextField TextField_ResultByTestCode) {
    this.TextField_ResultByTestCode = TextField_ResultByTestCode;
  }

  /**
   * @return the TitleProgram
   */
  public javax.swing.JLabel getTitleProgram() {
    return TitleProgram;
  }

  /**
   * @param TitleProgram the TitleProgram to set
   */
  public void setTitleProgram(javax.swing.JLabel TitleProgram) {
    this.TitleProgram = TitleProgram;
  }

  /**
   * @return the jPanel1
   */
  public javax.swing.JPanel getjPanel1() {
    return jPanel1;
  }

  /**
   * @param jPanel1 the jPanel1 to set
   */
  public void setjPanel1(javax.swing.JPanel jPanel1) {
    this.jPanel1 = jPanel1;
  }

  /**
   * @return the labelH_BatchExecuteSPSS
   */
  public javax.swing.JLabel getLabelH_BatchExecuteSPSS() {
    return labelH_BatchExecuteSPSS;
  }

  /**
   * @param labelH_BatchExecuteSPSS the labelH_BatchExecuteSPSS to set
   */
  public void setLabelH_BatchExecuteSPSS(javax.swing.JLabel labelH_BatchExecuteSPSS) {
    this.labelH_BatchExecuteSPSS = labelH_BatchExecuteSPSS;
  }

  /**
   * @return the labelH_Calendar
   */
  public javax.swing.JLabel getLabelH_Calendar() {
    return labelH_Calendar;
  }

  /**
   * @param labelH_Calendar the labelH_Calendar to set
   */
  public void setLabelH_Calendar(javax.swing.JLabel labelH_Calendar) {
    this.labelH_Calendar = labelH_Calendar;
  }

  /**
   * @return the labelH_Configuration
   */
  public javax.swing.JLabel getLabelH_Configuration() {
    return labelH_Configuration;
  }

  /**
   * @param labelH_Configuration the labelH_Configuration to set
   */
  public void setLabelH_Configuration(javax.swing.JLabel labelH_Configuration) {
    this.labelH_Configuration = labelH_Configuration;
  }

  /**
   * @return the labelH_ExecuteScript
   */
  public javax.swing.JLabel getLabelH_ExecuteScript() {
    return labelH_ExecuteScript;
  }

  /**
   * @param labelH_ExecuteScript the labelH_ExecuteScript to set
   */
  public void setLabelH_ExecuteScript(javax.swing.JLabel labelH_ExecuteScript) {
    this.labelH_ExecuteScript = labelH_ExecuteScript;
  }

  /**
   * @return the labelH_LastExecuteDate
   */
  public javax.swing.JLabel getLabelH_LastExecuteDate() {
    return labelH_LastExecuteDate;
  }

  /**
   * @param labelH_LastExecuteDate the labelH_LastExecuteDate to set
   */
  public void setLabelH_LastExecuteDate(javax.swing.JLabel labelH_LastExecuteDate) {
    this.labelH_LastExecuteDate = labelH_LastExecuteDate;
  }

  /**
   * @return the labelH_MainDIR
   */
  public javax.swing.JLabel getLabelH_MainDIR() {
    return labelH_MainDIR;
  }

  /**
   * @param labelH_MainDIR the labelH_MainDIR to set
   */
  public void setLabelH_MainDIR(javax.swing.JLabel labelH_MainDIR) {
    this.labelH_MainDIR = labelH_MainDIR;
  }

  /**
   * @return the labelH_MasterScript
   */
  public javax.swing.JLabel getLabelH_MasterScript() {
    return labelH_MasterScript;
  }

  /**
   * @param labelH_MasterScript the labelH_MasterScript to set
   */
  public void setLabelH_MasterScript(javax.swing.JLabel labelH_MasterScript) {
    this.labelH_MasterScript = labelH_MasterScript;
  }

  /**
   * @return the labelH_Product
   */
  public javax.swing.JLabel getLabelH_Product() {
    return labelH_Product;
  }

  /**
   * @param labelH_Product the labelH_Product to set
   */
  public void setLabelH_Product(javax.swing.JLabel labelH_Product) {
    this.labelH_Product = labelH_Product;
  }

  /**
   * @return the labelH_ResultAll
   */
  public javax.swing.JLabel getLabelH_ResultAll() {
    return labelH_ResultAll;
  }

  /**
   * @param labelH_ResultAll the labelH_ResultAll to set
   */
  public void setLabelH_ResultAll(javax.swing.JLabel labelH_ResultAll) {
    this.labelH_ResultAll = labelH_ResultAll;
  }

  /**
   * @return the labelH_ResultByTestCode
   */
  public javax.swing.JLabel getLabelH_ResultByTestCode() {
    return labelH_ResultByTestCode;
  }

  /**
   * @param labelH_ResultByTestCode the labelH_ResultByTestCode to set
   */
  public void setLabelH_ResultByTestCode(javax.swing.JLabel labelH_ResultByTestCode) {
    this.labelH_ResultByTestCode = labelH_ResultByTestCode;
  }

  /**
   * @return the labelH_status
   */
  public javax.swing.JLabel getLabelH_status() {
    return labelH_status;
  }

  /**
   * @param labelH_status the labelH_status to set
   */
  public void setLabelH_status(javax.swing.JLabel labelH_status) {
    this.labelH_status = labelH_status;
  }

  /**
   * @return the label_Status
   */
  public javax.swing.JLabel getLabel_Status() {
    return label_Status;
  }

  /**
   * @param label_Status the label_Status to set
   */
  public void setLabel_Status(javax.swing.JLabel label_Status) {
    this.label_Status = label_Status;
  }

  /**
   * @return the TextField_BatchMasterSPSS
   */
  public javax.swing.JTextField getTextField_BatchMasterSPSS() {
    return TextField_BatchMasterSPSS;
  }

  /**
   * @param TextField_BatchMasterSPSS the TextField_BatchMasterSPSS to set
   */
  public void setTextField_BatchMasterSPSS(javax.swing.JTextField TextField_BatchMasterSPSS) {
    this.TextField_BatchMasterSPSS = TextField_BatchMasterSPSS;
  }

  /**
   * @return the TextField_DBHostName
   */
  public javax.swing.JTextField getTextField_DBHostName() {
    return TextField_DBHostName;
  }

  /**
   * @param TextField_DBHostName the TextField_DBHostName to set
   */
  public void setTextField_DBHostName(javax.swing.JTextField TextField_DBHostName) {
    this.TextField_DBHostName = TextField_DBHostName;
  }

  /**
   * @return the TextField_DBName
   */
  public javax.swing.JTextField getTextField_DBName() {
    return TextField_DBName;
  }

  /**
   * @param TextField_DBName the TextField_DBName to set
   */
  public void setTextField_DBName(javax.swing.JTextField TextField_DBName) {
    this.TextField_DBName = TextField_DBName;
  }

  /**
   * @return the TextField_DBPassword
   */
  public javax.swing.JTextField getTextField_DBPassword() {
    return TextField_DBPassword;
  }

  /**
   * @param TextField_DBPassword the TextField_DBPassword to set
   */
  public void setTextField_DBPassword(javax.swing.JTextField TextField_DBPassword) {
    this.TextField_DBPassword = TextField_DBPassword;
  }

  /**
   * @return the TextField_DBPortName
   */
  public javax.swing.JTextField getTextField_DBPortName() {
    return TextField_DBPortName;
  }

  /**
   * @param TextField_DBPortName the TextField_DBPortName to set
   */
  public void setTextField_DBPortName(javax.swing.JTextField TextField_DBPortName) {
    this.TextField_DBPortName = TextField_DBPortName;
  }

  /**
   * @return the TextField_DBTableName
   */
  public javax.swing.JTextField getTextField_DBTableName() {
    return TextField_DBTableName;
  }

  /**
   * @param TextField_DBTableName the TextField_DBTableName to set
   */
  public void setTextField_DBTableName(javax.swing.JTextField TextField_DBTableName) {
    this.TextField_DBTableName = TextField_DBTableName;
  }

  /**
   * @return the TextField_DBUsername
   */
  public javax.swing.JTextField getTextField_DBUsername() {
    return TextField_DBUsername;
  }

  /**
   * @param TextField_DBUsername the TextField_DBUsername to set
   */
  public void setTextField_DBUsername(javax.swing.JTextField TextField_DBUsername) {
    this.TextField_DBUsername = TextField_DBUsername;
  }

  /**
   * @return the TextField_SPSSHostName
   */
  public javax.swing.JTextField getTextField_SPSSHostName() {
    return TextField_SPSSHostName;
  }

  /**
   * @param TextField_SPSSHostName the TextField_SPSSHostName to set
   */
  public void setTextField_SPSSHostName(javax.swing.JTextField TextField_SPSSHostName) {
    this.TextField_SPSSHostName = TextField_SPSSHostName;
  }

  /**
   * @return the TextField_SPSSLogFile
   */
  public javax.swing.JTextField getTextField_SPSSLogFile() {
    return TextField_SPSSLogFile;
  }

  /**
   * @param TextField_SPSSLogFile the TextField_SPSSLogFile to set
   */
  public void setTextField_SPSSLogFile(javax.swing.JTextField TextField_SPSSLogFile) {
    this.TextField_SPSSLogFile = TextField_SPSSLogFile;
  }

  /**
   * @return the TextField_SPSSPassword
   */
  public javax.swing.JTextField getTextField_SPSSPassword() {
    return TextField_SPSSPassword;
  }

  /**
   * @param TextField_SPSSPassword the TextField_SPSSPassword to set
   */
  public void setTextField_SPSSPassword(javax.swing.JTextField TextField_SPSSPassword) {
    this.TextField_SPSSPassword = TextField_SPSSPassword;
  }

  /**
   * @return the TextField_SPSSPortName
   */
  public javax.swing.JTextField getTextField_SPSSPortName() {
    return TextField_SPSSPortName;
  }

  /**
   * @param TextField_SPSSPortName the TextField_SPSSPortName to set
   */
  public void setTextField_SPSSPortName(javax.swing.JTextField TextField_SPSSPortName) {
    this.TextField_SPSSPortName = TextField_SPSSPortName;
  }

  /**
   * @return the TextField_SPSSScriptFile
   */
  public javax.swing.JTextField getTextField_SPSSScriptFile() {
    return TextField_SPSSScriptFile;
  }

  /**
   * @param TextField_SPSSScriptFile the TextField_SPSSScriptFile to set
   */
  public void setTextField_SPSSScriptFile(javax.swing.JTextField TextField_SPSSScriptFile) {
    this.TextField_SPSSScriptFile = TextField_SPSSScriptFile;
  }

  /**
   * @return the TextField_SPSSUserName
   */
  public javax.swing.JTextField getTextField_SPSSUserName() {
    return TextField_SPSSUserName;
  }

  /**
   * @param TextField_SPSSUserName the TextField_SPSSUserName to set
   */
  public void setTextField_SPSSUserName(javax.swing.JTextField TextField_SPSSUserName) {
    this.TextField_SPSSUserName = TextField_SPSSUserName;
  }

  /**
   * @return the labelH_BatchExecuteSPSS1
   */
  public javax.swing.JLabel getLabelH_BatchExecuteSPSS1() {
    return labelH_BatchExecuteSPSS1;
  }

  /**
   * @param labelH_BatchExecuteSPSS1 the labelH_BatchExecuteSPSS1 to set
   */
  public void setLabelH_BatchExecuteSPSS1(javax.swing.JLabel labelH_BatchExecuteSPSS1) {
    this.labelH_BatchExecuteSPSS1 = labelH_BatchExecuteSPSS1;
  }

  /**
   * @return the labelH_BatchExecuteSPSS2
   */
  public javax.swing.JLabel getLabelH_BatchExecuteSPSS2() {
    return labelH_BatchExecuteSPSS2;
  }

  /**
   * @param labelH_BatchExecuteSPSS2 the labelH_BatchExecuteSPSS2 to set
   */
  public void setLabelH_BatchExecuteSPSS2(javax.swing.JLabel labelH_BatchExecuteSPSS2) {
    this.labelH_BatchExecuteSPSS2 = labelH_BatchExecuteSPSS2;
  }

  /**
   * @return the labelH_BatchMasterSPSS
   */
  public javax.swing.JLabel getLabelH_BatchMasterSPSS() {
    return labelH_BatchMasterSPSS;
  }

  /**
   * @param labelH_BatchMasterSPSS the labelH_BatchMasterSPSS to set
   */
  public void setLabelH_BatchMasterSPSS(javax.swing.JLabel labelH_BatchMasterSPSS) {
    this.labelH_BatchMasterSPSS = labelH_BatchMasterSPSS;
  }

  /**
   * @return the labelH_BatchMasterSPSS1
   */
  public javax.swing.JLabel getLabelH_BatchMasterSPSS1() {
    return labelH_BatchMasterSPSS1;
  }

  /**
   * @param labelH_BatchMasterSPSS1 the labelH_BatchMasterSPSS1 to set
   */
  public void setLabelH_BatchMasterSPSS1(javax.swing.JLabel labelH_BatchMasterSPSS1) {
    this.labelH_BatchMasterSPSS1 = labelH_BatchMasterSPSS1;
  }

  /**
   * @return the labelH_BatchMasterSPSS2
   */
  public javax.swing.JLabel getLabelH_BatchMasterSPSS2() {
    return labelH_BatchMasterSPSS2;
  }

  /**
   * @param labelH_BatchMasterSPSS2 the labelH_BatchMasterSPSS2 to set
   */
  public void setLabelH_BatchMasterSPSS2(javax.swing.JLabel labelH_BatchMasterSPSS2) {
    this.labelH_BatchMasterSPSS2 = labelH_BatchMasterSPSS2;
  }

  /**
   * @return the labelH_ExecuteScript1
   */
  public javax.swing.JLabel getLabelH_ExecuteScript1() {
    return labelH_ExecuteScript1;
  }

  /**
   * @param labelH_ExecuteScript1 the labelH_ExecuteScript1 to set
   */
  public void setLabelH_ExecuteScript1(javax.swing.JLabel labelH_ExecuteScript1) {
    this.labelH_ExecuteScript1 = labelH_ExecuteScript1;
  }

  /**
   * @return the labelH_ExecuteScript2
   */
  public javax.swing.JLabel getLabelH_ExecuteScript2() {
    return labelH_ExecuteScript2;
  }

  /**
   * @param labelH_ExecuteScript2 the labelH_ExecuteScript2 to set
   */
  public void setLabelH_ExecuteScript2(javax.swing.JLabel labelH_ExecuteScript2) {
    this.labelH_ExecuteScript2 = labelH_ExecuteScript2;
  }

  /**
   * @return the labelH_Product1
   */
  public javax.swing.JLabel getLabelH_Product1() {
    return labelH_Product1;
  }

  /**
   * @param labelH_Product1 the labelH_Product1 to set
   */
  public void setLabelH_Product1(javax.swing.JLabel labelH_Product1) {
    this.labelH_Product1 = labelH_Product1;
  }

  /**
   * @return the labelH_Product2
   */
  public javax.swing.JLabel getLabelH_Product2() {
    return labelH_Product2;
  }

  /**
   * @param labelH_Product2 the labelH_Product2 to set
   */
  public void setLabelH_Product2(javax.swing.JLabel labelH_Product2) {
    this.labelH_Product2 = labelH_Product2;
  }

  /**
   * @return the labelH_ResultAll1
   */
  public javax.swing.JLabel getLabelH_ResultAll1() {
    return labelH_ResultAll1;
  }

  /**
   * @param labelH_ResultAll1 the labelH_ResultAll1 to set
   */
  public void setLabelH_ResultAll1(javax.swing.JLabel labelH_ResultAll1) {
    this.labelH_ResultAll1 = labelH_ResultAll1;
  }

  /**
   * @return the labelH_ResultAll2
   */
  public javax.swing.JLabel getLabelH_ResultAll2() {
    return labelH_ResultAll2;
  }

  /**
   * @param labelH_ResultAll2 the labelH_ResultAll2 to set
   */
  public void setLabelH_ResultAll2(javax.swing.JLabel labelH_ResultAll2) {
    this.labelH_ResultAll2 = labelH_ResultAll2;
  }

  /**
   * @return the labelH_ResultByTestCode1
   */
  public javax.swing.JLabel getLabelH_ResultByTestCode1() {
    return labelH_ResultByTestCode1;
  }

  /**
   * @param labelH_ResultByTestCode1 the labelH_ResultByTestCode1 to set
   */
  public void setLabelH_ResultByTestCode1(javax.swing.JLabel labelH_ResultByTestCode1) {
    this.labelH_ResultByTestCode1 = labelH_ResultByTestCode1;
  }

  /**
   * @return the labelH_ResultByTestCode2
   */
  public javax.swing.JLabel getLabelH_ResultByTestCode2() {
    return labelH_ResultByTestCode2;
  }

  /**
   * @param labelH_ResultByTestCode2 the labelH_ResultByTestCode2 to set
   */
  public void setLabelH_ResultByTestCode2(javax.swing.JLabel labelH_ResultByTestCode2) {
    this.labelH_ResultByTestCode2 = labelH_ResultByTestCode2;
  }

  /**
   * @return the label_excTime
   */
  public javax.swing.JLabel getLabel_excTime() {
    return label_excTime;
  }

  /**
   * @param label_excTime the label_excTime to set
   */
  public void setLabel_excTime(javax.swing.JLabel label_excTime) {
    this.label_excTime = label_excTime;
  }
}
